services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_APP=main.py
    image: michaelwayne/cyb5272-flaskapp:latest

    ports:
      - "5050:5000"
    depends_on:
      db:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=onlinesystem
    volumes:
      - ./app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: mysql:8.0

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: onlinesystem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s

  db_init:
    build:
      context: .
      dockerfile: Dockerfile
    image: michaelwayne/cyb5272-db-init:latest

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
    working_dir: /app
    command: python db-init/init_admin.py

volumes:
  mysql_data:
