services:
  flaskapp_with_ratelimit:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=onlinesystem
    volumes:
      - ./app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5001

  flaskapp_no_ratelimit:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main_no_ratelimit.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=onlinesystem
    volumes:
      - ./app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5002

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: onlinesystem
    ports:
      - "3306:3306"
    volumes:
      # - ./db-init:/docker-entrypoint-initdb.d
      - ./app/db-init/onlinesystem.sql:/docker-entrypoint-initdb.d/onlinesystem.sql
